# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'canny.ui'
#
# Created by: PyQt5 UI code generator 5.15.6
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(868, 600)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(40, 20, 681, 451))
        self.label.setObjectName("label")
        self.lowSlider = QtWidgets.QSlider(self.centralwidget)
        self.lowSlider.setGeometry(QtCore.QRect(40, 490, 721, 16))
        self.lowSlider.setMaximum(300)
        self.lowSlider.setOrientation(QtCore.Qt.Horizontal)
        self.lowSlider.setObjectName("lowSlider")
        self.highSlider = QtWidgets.QSlider(self.centralwidget)
        self.highSlider.setGeometry(QtCore.QRect(40, 520, 721, 16))
        self.highSlider.setMaximum(300)
        self.highSlider.setOrientation(QtCore.Qt.Horizontal)
        self.highSlider.setObjectName("highSlider")
        self.pushButton = QtWidgets.QPushButton(self.centralwidget)
        self.pushButton.setGeometry(QtCore.QRect(788, 500, 71, 25))
        self.pushButton.setObjectName("pushButton")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 868, 22))
        self.menubar.setObjectName("menubar")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.label.setText(_translate("MainWindow", "TextLabel"))
        self.pushButton.setText(_translate("MainWindow", "stop"))
